name: Deploy Backend to EC2

on:
  push:
    branches: [master]  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Deploy via SSH
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/backend
            git pull origin master
            npm install
            pm2 restart all || pm2 start index.js
          EOF
